<?php
    /** @var Linkedin_Testimonials_Block_Create $this */
?>

<div class="testimonials-create">
    <div class="page-title">
        <h1><?php echo $this->__('Post Your Testimonial') ?></h1>
    </div>
    <?php echo $this->getMessagesBlock()->toHtml() ?>
    <form action="<?php echo $this->getPostActionUrl() ?>" method="post" id="form-validate">
        <div class="fieldset">
            <input type="hidden" name="form_key" value="<?php echo Mage::getSingleton('core/session')->getFormKey() ?>" />
            <ul class="form-list">
                <li>
                    <label for="message" class="required"><em>*</em><?php echo $this->__('Write your testimonial') ?></label>
                    <div class="input-box">
                        <textarea name="message" id="message"  class="input-text required-entry"><?php echo $this->escapeHtml($this->getFormData()->getMessage()) ?></textarea>
                    </div>
                </li>
            </ul>
        </div>

        <div class="buttons-set">
            <p class="back-link"><a href="<?php echo $this->escapeUrl($this->getBackUrl()) ?>" class="back-link"><small>&laquo; </small><?php echo $this->__('Back') ?></a></p>
            <button type="submit" title="<?php echo Mage::helper('core')->quoteEscape($this->__('Submit')) ?>" class="button"><span><span><?php echo $this->__('Submit') ?></span></span></button>
        </div>
    </form>

    <script type="text/javascript">
        //<![CDATA[
        var dataForm = new VarienForm('form-validate', true);
        //]]>
    </script>
</div>